### ISSUE TITLE
User gets Logged In on SignUP

### ISSUE THREAD

**Issue by charliehustlr1792** [SanchitGeez/Investra#1]
User gets automatically logged in when signed up. Can you please assign this issue to me also add hacktoberfest and gssoc extd labels

**Comment by SanchitGeez** [comment]
Go Ahead with it!

**Comment by SanchitGeez** [comment]
@charliehustlr1792 Still working on it?

**Comment by charliehustlr1792** [comment]
Yes almost done

**Comment by charliehustlr1792** [comment]
@SanchitGeez the user is redirected to the dashboard after signup but the dashboard is not rendering (appearing full black) ....Can you suggest some changes pls

**Comment by SanchitGeez** [comment]
> @SanchitGeez the user is redirected to the dashboard after signup but the dashboard is not rendering (appearing full black) ....Can you suggest some changes pls

Try triggering the login api(with the same credentials) instead of directly redirecting to dashboard

**Comment by charliehustlr1792** [comment]
@SanchitGeez pls review the pr
