### ISSUE TITLE
Token Validation Improvements in `isAuth` Middleware

### ISSUE THREAD

**Issue by GAURAV8520** [SanchitGeez/Investra#11]
# Token Validation Improvements in `isAuth` Middleware

## Description
The current `isAuth` middleware has areas for improvement regarding token validation and security. This section outlines the necessary changes to enhance the token validation process and secure the JWT secret.

## Tasks

1. **Improve Token Existence Check**
   - Replace the current token check:
     ```javascript
     if(token != 0)
     ```
     with a more reliable and readable check:
     ```javascript
     if (!token) return res.status(401).send("Login first");
     ```

2. **Add Error Handling for Invalid/Expired Tokens**
   - Use a `try-catch` block around the `jwt.verify()` function to properly handle invalid or expired tokens:
     ```javascript
     try {
       const decoded = jwt.verify(token, process.env.JWT_SECRET);
       req.activeUser = await UserModel.findById(decoded._id);
       next();
     } catch (error) {
       return res.status(401).send("Invalid or expired token");
     }
     ```

3. **Move Hardcoded JWT Secret to Environment Variable**
   - Replace the hardcoded JWT secret:
     ```javascript
     "jwtrandomstring"
     ```
     with an environment variable for better security:
     ```javascript
     const decoded = jwt.verify(token, process.env.JWT_SECRET);
     ```

   - Ensure that the JWT secret is stored in the `.env` file:
     ```
     JWT_SECRET=jwtrandomstring
     ```

## Expected Outcome
- A more secure and reliable token validation process, reducing the risk of unauthorized access due to token-related issues.

## Issue Assignment
Please assign this issue to me for implementation.

**Comment by GAURAV8520** [comment]
@SanchitGeez can you please assign this issue to me and give it the gssoc-ext , hacktoberfest and the level labels.

**Comment by SanchitGeez** [comment]
> @SanchitGeez can you please assign this issue to me and give it the gssoc-ext , hacktoberfest and the level labels.

Go ahead!!
