### ISSUE TITLE
Login page not responsive on mobile 

### ISSUE THREAD

**Issue by Sureshwebdeveloper** [SanchitGeez/Investra#16]
![Screenshot_2024-10-02-22-31-23-616_com android chrome](https://github.com/user-attachments/assets/0ceb3ca4-ae64-4e7b-9e68-594ae76732b1)

Its only showing on brand name not a login or signup 
If you assign to me I will fix it and add a label the gssocext and hactoberfest badges and add a level as well
@SanchitGeez

**Comment by AskitEndo** [comment]
@SanchitGeez Can I also work on this?

**Comment by SanchitGeez** [comment]
@Sureshwebdeveloper are you still working on this?

**Comment by Sureshwebdeveloper** [comment]
No bro I am completed and  pulled you have merged but merge place you dont have aded not added gssoc-ext gssoc level2 hacktoberfest hacktoberfest-accepted labels

**Comment by Sureshwebdeveloper** [comment]
No bro I am completed and  pulled you have merged but merge place you dont have aded not added gssoc-ext gssoc level2 hacktoberfest hacktoberfest-accepted labels

**Comment by Sureshwebdeveloper** [comment]
Login page not responsive on mobile #16
and responsive design added to login and signup page #39 
both has been assigned to me I will fix on that via #39 you have already merged
