### ISSUE TITLE
ReferenceError: FaEye is not defined

### ISSUE THREAD

**Issue by rishuishind** [SanchitGeez/Investra#19]
In the home page of the website it shows FaEye is not defined, this is because you're using it on the client but have not imported it from the UI library which you're using, I saw you're using radix UI react icons
I've uploaded the screenshot of the error and the reference to it, I'll fix this and will raise a PR 
<img width="957" alt="Screenshot 2024-10-03 at 12 12 08 PM" src="https://github.com/user-attachments/assets/4f87cd6c-df81-415f-9b82-581f95c0aaba">
<img width="565" alt="Screenshot 2024-10-03 at 12 12 25 PM" src="https://github.com/user-attachments/assets/30278468-a56e-4fe4-8930-5f40140b7ca0">

**Comment by SanchitGeez** [comment]
Should i assign it to you?

**Comment by rishuishind** [comment]
I have fixed that issue and raised a PR

**Comment by SanchitGeez** [comment]
> I have fixed that issue and raised a PR

Check for changes requested

**Comment by rishuishind** [comment]
I have already changed the code, which is working fine on home page, I have raised a PR but the checks are failing because of errors in your existing codebase, you can merge my PR by looking what have I changed in it.

**Comment by SanchitGeez** [comment]
> I have already changed the code, which is working fine on home page, I have raised a PR but the checks are failing because of errors in your existing codebase, you can merge my PR by looking what have I changed in it.

Okay good job. Although I was reffering to that you have removed CONTRIBUTING.md file by mistake. I have handled it for now.
