### ISSUE TITLE
Add cursor pointer on clickable links and buttons

### ISSUE THREAD

**Issue by Rahul7raj** [SanchitGeez/Investra#23]
# Issue
- Currently, clickable buttons and links are not visually separated from other UI components, making it difficult for users to identify them as interactive elements.

## Recording

https://github.com/user-attachments/assets/e919da14-fc19-4392-8bdb-9883eac454d1

# Proposed Solution
- I propose adding a `cursor: pointer` style to clickable links and buttons to clearly indicate they are interactive. After implementing this, the UI will be more intuitive for users. The result will look like this:

https://github.com/user-attachments/assets/a63c6d2e-3abf-447e-b625-83245c93dc87

**Comment by SanchitGeez** [comment]
@Rahul7raj go ahead
