### ISSUE TITLE
Adding forget password functionality 

### ISSUE THREAD

**Issue by zakie2003** [SanchitGeez/Investra#5]
The login lacks forget password functionality please assign mei the task for it under gssoc extended

**Comment by SanchitGeez** [comment]
All the best!

**Comment by zakie2003** [comment]
Hi @SanchitGeez , just wanted to know did you review my code in another branch.If you are facing any issues lemme know.

**Comment by SanchitGeez** [comment]
> Hi @SanchitGeez , just wanted to know did you review my code in another branch.If you are facing any issues lemme know.

It works great!! Although can you specify what should I add in EMAIL and PASSWORD in the .env.

**Comment by zakie2003** [comment]
Aahh you might be knowing how node mailer works right? the .env file contains the email by which the OTP is being sent and the password is app-password which you need to set up from the email id which by which you want to send otp.Never the less you may merge it with the main branch for now,I will be happy to assist you setting up the app password if you don't know

**Comment by SanchitGeez** [comment]
> Aahh you might be knowing how node mailer works right? the .env file contains the email by which the OTP is being sent and the password is app-password which you need to set up from the email id which by which you want to send otp.Never the less you may merge it with the main branch for now,I will be happy to assist you setting up the app password if you don't know

Okay @zakie2003 merging to main. Good job. Altthough for future commits remove the .env files from git tracking. We'll make necessary changes later if needed
