### ISSUE TITLE
Add Regex Check in Password Field

### ISSUE THREAD

**Issue by Rizvi-Faiz** [SanchitGeez/Investra#50]
### Issue: Add Regex Check in Password Field

**Description:**
The password field in the user registration form currently lacks validation based on password complexity. To enhance security, we need to implement a regex check to enforce specific password requirements.

**Acceptance Criteria:**
- Implement regex validation for the password field.
- The password must:
  - Be at least 8 characters long.
  - Include at least one uppercase letter.
  - Include at least one lowercase letter.
  - Include at least one number.
  - Include at least one special character (e.g., `@`, `#`, `!`, etc.).

**Implementation Details:**
1. Add a regex pattern in the password field validation.
2. Display a validation error message if the password doesn't meet the criteria.
3. Ensure the form prevents submission if the validation fails.

**Comment by Rizvi-Faiz** [comment]
@SanchitGeez Plaease assign this issue to me

**Comment by SanchitGeez** [comment]
@Rizvi-Faiz Bro I am busy for a couple of days, I saw all your messages and I will merge all the PR's and update the labels in 2 days. DW you will get the points for those

**Comment by Rizvi-Faiz** [comment]
@SanchitGeez ok and do add the correct ones according to my issues 
and do add the correct labels like "level3" not "level-3".
my prs are #27 
#26 
#17 
#14 
#55
