### ISSUE TITLE
(Enhancement) (level1) Add Github Greetings Bot

### ISSUE THREAD

**Issue by KiranBaliga** [SanchitGeez/Investra#71]
Hey 🥳 Looks like an amazing project idea! I see this repo lacks a small enhancement Github Greetings bot that sends auto messages to greet new users when they raise a PR or an issue. Let me know if you would like this level1 set up! Please assign to me if interested! (GSSoC24-Ext Contribution)

**Comment by SanchitGeez** [comment]
start working ...i'll assign the labels in a couple of days

**Comment by KiranBaliga** [comment]
@SanchitGeez Please review the PR and action accordingly. Please add level1 and gssoc-ext labels to the linked PR. Thank you!
