### ISSUE TITLE
adding chatbot ✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [SanchitGeez/Investra#72]
i want to add a chatbot which will be fine tuned to the website and answer the user about stocks.
@SanchitGeez can you please assign this task to me.
thank you!

**Comment by SanchitGeez** [comment]
start working ...i'll assign the labels in a couple of days

**Comment by T-Rahul-prabhu-38** [comment]
@SanchitGeez i have created the PR , can you please review it.

**Comment by T-Rahul-prabhu-38** [comment]
> I am interested but, please provide more info.

sorry i didnt understand what ur referencing to. are asking about the PR i made?

**Comment by T-Rahul-prabhu-38** [comment]
i have finished it , but if u want to explore that , u can check out botpress or chatbase.co
