### ISSUE TITLE
Add Percentage Profit for each stock

### ISSUE THREAD

**Issue by SanchitGeez** [SanchitGeez/Investra#8]
Add the profit earned in percentage(for each stock seperately) and add it to the Stock card somewhere
![image](https://github.com/user-attachments/assets/d8ac0fd0-f5e1-45e9-9d02-0de180bf5449)

**Comment by Rizvi-Faiz** [comment]
@SanchitGeez  can you assign this issue to me

**Comment by SanchitGeez** [comment]
@Rizvi-Faiz Go Ahead!!

**Comment by Rizvi-Faiz** [comment]
can you assign me the other two issues which i asked
